### ISSUE TITLE
terraform-provider-huaweicloud plugin crashed

### ISSUE THREAD

**Issue by nik-afa** [huaweicloud/terraform-provider-huaweicloud#1526]
Hi, when i try install MRS cluster, get error, and tf state dont save

### Terraform Version
```
Terraform v0.15.1
on darwin_amd64
+ provider registry.terraform.io/huaweicloud/huaweicloud v1.28.1
```
### HCL
```
resource "huaweicloud_mapreduce_cluster" "clickhouse-stage" {
  availability_zone     = data.huaweicloud_availability_zones.ecsaz.names[1]
  name                  = "clickhouse-stage"
  version               = "MRS 3.0.5"
  type                  = "CUSTOM"
  component_list        = ["ClickHouse", "ZooKeeper", "Hadoop", "Ranger"]
  enterprise_project_id = local.enterprise_project_id
  region                = local.region
  safe_mode             = false
  manager_admin_pass    = ""
  node_admin_pass       = ""
  vpc_id                = data.terraform_remote_state.vpc.outputs.vpc_id
  subnet_id             = data.terraform_remote_state.vpc.outputs.subnet_id
  template_id           = "mgmt_control_combined_v2"
  log_collection        = true
  # SG all_open
  security_group_ids = ["c11765e3-vc43-443c-952e-515c06e54d18"]

  master_nodes {
    flavor            = "c6.4xlarge.2.linux.bigdata"
    node_number       = 3
    root_volume_type  = "SAS"
    root_volume_size  = 480
    data_volume_type  = "SAS"
    data_volume_size  = 600
    data_volume_count = 1
    assigned_roles = [
      "OMSServer:1,2",
      "SlapdServer:1,2",
      "KerberosServer:1,2",
      "KerberosAdmin:1,2",
      "quorumpeer:1,2,3",
      "NameNode:2,3",
      "Zkfc:2,3",
      "JournalNode:1,2,3",
      "ResourceManager:2,3",
      "JobHistoryServer:3",
      "DBServer:1,3",
      "HttpFS:1,3",
      "TimelineServer:3",
      "RangerAdmin:1,2",
      "UserSync:2",
      "TagSync:2",
      "KerberosClient",
      "SlapdClient",
      "meta"
    ]
  }
  custom_nodes {
    group_name        = "node_group_1"
    flavor            = "c6.4xlarge.2.linux.bigdata"
    node_number       = 3
    root_volume_type  = "SAS"
    root_volume_size  = 480
    data_volume_type  = "SAS"
    data_volume_size  = 600
    data_volume_count = 1
    assigned_roles = [
      "DataNode",
      "NodeManager",
      "meta",
      "KerberosClient",
      "SlapdClient"
    ]
  }
  custom_nodes {
    group_name        = "ClickHouse"
    flavor            = "c6.4xlarge.2.linux.bigdata"
    node_number       = 2
    root_volume_type  = "SAS"
    root_volume_size  = 480
    data_volume_type  = "SAS"
    data_volume_size  = 600
    data_volume_count = 1
    assigned_roles = [
      "clickhouse",
      "meta",
      "KerberosClient",
      "SlapdClient"
    ]
  }
  timeouts {
    create = "2h"
    update = "2h"
  }
}
```

### Output
```
│ Error: Plugin did not respond
│
│   with huaweicloud_mapreduce_cluster.clickhouse-stage,
│   on clickhouse-stage.tf line 1, in resource "huaweicloud_mapreduce_cluster" "clickhouse-stage":
│    1: resource "huaweicloud_mapreduce_cluster" "clickhouse-stage" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-huaweicloud_v1.28.1 plugin:

panic: interface conversion: interface {} is []interface {}, not []string

goroutine 25 [running]:
github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/services/mrs.parseAssignedRoles(0xc000f66c80, 0xc00101f1b0, 0xc, 0x1, 0xc000536678, 0x3, 0x3)
	github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/services/mrs/resource_huaweicloud_mapreduce_cluster.go:709 +0x333
github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/services/mrs.setMrsClusterNodeGroups(0xc000f66c80, 0xc00101c190, 0xc0008a1000, 0x0, 0x2ca35a8)
	github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/services/mrs/resource_huaweicloud_mapreduce_cluster.go:681 +0x705
github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/services/mrs.resourceMRSClusterV2Read(0xc000f66c80, 0x22dba40, 0xc00097dba0, 0x0, 0x1)
	github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/services/mrs/resource_huaweicloud_mapreduce_cluster.go:796 +0xb1e
github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/services/mrs.resourceMRSClusterV2Create(0xc000f66c80, 0x22dba40, 0xc00097dba0, 0xa, 0xffffffffffffffff)
	github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/services/mrs/resource_huaweicloud_mapreduce_cluster.go:568 +0x1448
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0009e6700, 0x2529968, 0xc0001197c0, 0xc000f66c80, 0x22dba40, 0xc00097dba0, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:318 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0009e6700, 0x2529968, 0xc0001197c0, 0xc000f60230, 0xc00011b240, 0x22dba40, 0xc00097dba0, 0x0, 0x0, 0x0, ...)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:456 +0x67b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00000c0a8, 0x2529968, 0xc0001197c0, 0xc00008c910, 0xc0001197c0, 0x226b7e0, 0xc000f4c100)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/grpc_provider.go:955 +0x8ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc000ad41c0, 0x2529a10, 0xc0001197c0, 0xc000f60000, 0xc000ad41c0, 0xc000f4c1b0, 0xc0006daba0)
	github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x226b7e0, 0xc000ad41c0, 0x2529a10, 0xc000f4c1b0, 0xc000664300, 0x0, 0x2529a10, 0xc000f4c1b0, 0xc000f5e000, 0xe7c)
	github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00013b6c0, 0x2535778, 0xc000102d80, 0xc000f52000, 0xc000be9320, 0x2d018e0, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc00013b6c0, 0x2535778, 0xc000102d80, 0xc000f52000, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000a1e360, 0xc00013b6c0, 0x2535778, 0xc000102d80, 0xc000f52000)
	google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-huaweicloud_v1.28.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by nik-afa** [comment]
Can someone say something about this?

**Comment by hmbig2** [comment]
> Can someone say something about this?

This problem will be fixed in the next version which released at the end of the month.  Sorry for the inconvenience caused.
